let tableDataPivot = {
  nw3J6TOHaMJ: {
    displayName: "Cabo Delgado",
    pis: {
      WIWANANA: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      SERNAP: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
    },
  },
  ebNQelMgKP2: {
    displayName: "Gaza",
    pis: {
      UNIDOS: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      ABEVAMO: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      SERNAP: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
    },
  },
  zroLfm6XdvJ: {
    displayName: "Inhambane",
    pis: {
      UTOMI: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      LAMBDA: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      SERNAP: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
    },
  },
  vR8ik8LYLG0: {
    displayName: "Manica",
    pis: {
      OMES: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      LAMBDA: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      KWAEDJA: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      SERNAP: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
    },
  },
  cRWJ2ytimX5: {
    displayName: "Maputo Cidade",
    pis: {
      ABEVAMO: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      SERNAP: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      LAMBDA: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      UNIDOS: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
    },
  },
  VjPKrjOYV5q: {
    displayName: "Maputo Provincia",
    pis: {
      UNGAGODOLI: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      LAMBDA: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      UNIDOS: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      SERNAP: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
    },
  },
  NWA62AZqgyQ: {
    displayName: "Nampula",
    pis: {
      LAMBDA: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      ICRHM: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      SERNAP: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
    },
  },
  TQCU3OJrY1G: {
    displayName: "Niassa",
    pis: {
      ICRHM: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      SERNAP: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
    },
  },
  FwyWyxJ4X3r: {
    displayName: "Sofala",
    pis: {
      TAKAEZANA: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      SERNAP: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      FANBIDZANAI: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      LAMBDA: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
    },
  },
  NJSkNxfOJ1g: {
    displayName: "Tete",
    pis: {
      LAMBDA: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      SERNAP: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      OMES: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
    },
  },
  rqyrNjhbq6a: {
    displayName: "Zambézia",
    pis: {
      OMES: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      LAMBDA: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
      SERNAP: {
        vbg: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
        vpi: {
          vpsicologica: 0,
          veconomica: 0,
          vsexual: 0,
          vfisica: 0,
          positivos: 0,
          rastreados: 0,
          prm: 0,
          ipaj: 0,
          us: 0,
          apoiosocial: 0,
          ppe: 0,
          its: 0,
          hiv: 0,
          ce: 0,
        },
      },
    },
  },
};

export default tableDataPivot;
